from .prompt_nodes import NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS
from .prompt_nodes import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools import NODE_CLASS_MAPPINGS as IMAGE_TOOLS_NODE_CLASS_MAPPINGS
from .image_tools import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_TOOLS_NODE_DISPLAY_NAME_MAPPINGS
from .llm_image_reverse import LLM_IMAGE_REVERSE_NODE_CLASS_MAPPINGS
from .llm_image_reverse import LLM_IMAGE_REVERSE_NODE_DISPLAY_NAME_MAPPINGS
from .llm_image_reverse import VIDEO_OPTIMIZER_NODE_CLASS_MAPPINGS
from .llm_image_reverse import VIDEO_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS
from .video_resolution_processor import NODE_CLASS_MAPPINGS as VIDEO_RESOLUTION_NODE_MAPPINGS
from .video_resolution_processor import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_RESOLUTION_DISPLAY_MAPPINGS



NODE_CLASS_MAPPINGS = {
    **PROMPT_NODE_CLASS_MAPPINGS,    
    **IMAGE_TOOLS_NODE_CLASS_MAPPINGS,
    **LLM_IMAGE_REVERSE_NODE_CLASS_MAPPINGS,
    **VIDEO_OPTIMIZER_NODE_CLASS_MAPPINGS,
    **VIDEO_RESOLUTION_NODE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,    
    **IMAGE_TOOLS_NODE_DISPLAY_NAME_MAPPINGS,  
    **LLM_IMAGE_REVERSE_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_RESOLUTION_DISPLAY_MAPPINGS,
}

__all__ = ("NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS")
