from .prompt_nodes import NODE_CLASS_MAPPINGS as PROMPT_NODE_CLASS_MAPPINGS
from .prompt_nodes import NODE_DISPLAY_NAME_MAPPINGS as PROMPT_NODE_DISPLAY_NAME_MAPPINGS
from .image_tools import NODE_CLASS_MAPPINGS as IMAGE_TOOLS_NODE_CLASS_MAPPINGS
from .image_tools import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_TOOLS_NODE_DISPLAY_NAME_MAPPINGS
from .llm_image_reverse import LLM_IMAGE_REVERSE_NODE_CLASS_MAPPINGS
from .llm_image_reverse import LLM_IMAGE_REVERSE_NODE_DISPLAY_NAME_MAPPINGS
from .llm_image_reverse import VIDEO_OPTIMIZER_NODE_CLASS_MAPPINGS
from .llm_image_reverse import VIDEO_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS
from .video_resolution_processor import NODE_CLASS_MAPPINGS as VIDEO_RESOLUTION_NODE_MAPPINGS
from .video_resolution_processor import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_RESOLUTION_DISPLAY_MAPPINGS
from .audio import AUDIO_NODE_CLASS_MAPPINGS, AUDIO_NODE_DISPLAY_NAME_MAPPINGS
from .image_string_nodes import NODE_CLASS_MAPPINGS as IMAGE_STRING_NODE_CLASS_MAPPINGS
from .image_string_nodes import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_STRING_NODE_DISPLAY_NAME_MAPPINGS
from .video import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS
from .video import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS



NODE_CLASS_MAPPINGS = {
    **PROMPT_NODE_CLASS_MAPPINGS,    
    **IMAGE_TOOLS_NODE_CLASS_MAPPINGS,
    **LLM_IMAGE_REVERSE_NODE_CLASS_MAPPINGS,
    **VIDEO_OPTIMIZER_NODE_CLASS_MAPPINGS,
    **VIDEO_RESOLUTION_NODE_MAPPINGS,
    **AUDIO_NODE_CLASS_MAPPINGS,
    **IMAGE_STRING_NODE_CLASS_MAPPINGS,
    **VIDEO_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_NODE_DISPLAY_NAME_MAPPINGS,    
    **IMAGE_TOOLS_NODE_DISPLAY_NAME_MAPPINGS,  
    **LLM_IMAGE_REVERSE_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_OPTIMIZER_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_RESOLUTION_DISPLAY_MAPPINGS,
    **AUDIO_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_STRING_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ("NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY")
