from .random_prompt_node import NODE_CLASS_MAPPINGS as RANDOM_PROMPT_CLASS_MAPPINGS
from .random_prompt_node import NODE_DISPLAY_NAME_MAPPINGS as RANDOM_PROMPT_DISPLAY_MAPPINGS


NODE_CLASS_MAPPINGS = {
    **RANDOM_PROMPT_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **RANDOM_PROMPT_DISPLAY_MAPPINGS,
}

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]