from .audio_split_node import NODE_CLASS_MAPPINGS as AUDIO_SPLIT_NODE_CLASS_MAPPINGS
from .audio_split_node import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_SPLIT_NODE_DISPLAY_NAME_MAPPINGS
from .audio_select_node import NODE_CLASS_MAPPINGS as AUDIO_SELECT_NODE_CLASS_MAPPINGS
from .audio_select_node import NODE_DISPLAY_NAME_MAPPINGS as AUDIO_SELECT_NODE_DISPLAY_NAME_MAPPINGS

AUDIO_NODE_CLASS_MAPPINGS = {
    **AUDIO_SPLIT_NODE_CLASS_MAPPINGS,
    **AUDIO_SELECT_NODE_CLASS_MAPPINGS,
}

AUDIO_NODE_DISPLAY_NAME_MAPPINGS = {
    **AUDIO_SPLIT_NODE_DISPLAY_NAME_MAPPINGS,
    **AUDIO_SELECT_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = (
    "AUDIO_NODE_CLASS_MAPPINGS",
    "AUDIO_NODE_DISPLAY_NAME_MAPPINGS",
)